services:
  wechat:
    build: .
    ports:
      - "8260:8260"
    env_file:
      - wechat_prod.env
    extra_hosts:
      - "nmtr.site:host-gateway"
    volumes:
      - /usr/share/py-projects/next-train-bot/data:/app/data